# Generated by Django 2.0.7 on 2018-07-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadsheetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed', models.IntegerField()),
                ('clr', models.IntegerField()),
                ('spread', models.IntegerField()),
                ('percentage_of_available', models.IntegerField()),
                ('rand_loan_amount', models.IntegerField()),
                ('rand_term', models.IntegerField()),
                ('rand_rate', models.IntegerField()),
                ('btc_usd_price', models.IntegerField()),
                ('eth_usd_price', models.IntegerField()),
                ('btc_eth_price', models.IntegerField()),
                ('demand', models.IntegerField()),
                ('supply', models.IntegerField()),
                ('ratio_demand_supply', models.IntegerField()),
                ('number_of_bids_demand', models.IntegerField()),
                ('number_of_offers_supply', models.IntegerField()),
                ('weighted_average_rate', models.IntegerField()),
                ('simple_average_rate', models.IntegerField()),
                ('demand_avg_rate', models.IntegerField()),
                ('avg_clr_3_hr', models.IntegerField()),
                ('avg_clr_12_hr', models.IntegerField()),
                ('avg_clr_24_hr', models.IntegerField()),
                ('avg_clr_48_hr', models.IntegerField()),
                ('avg_clr_7_days', models.IntegerField()),
                ('avg_clr_3_hr_vs_6', models.IntegerField()),
                ('avg_clr_6_hr_vs_12', models.IntegerField()),
                ('avg_clr_12_hr_vs_24', models.IntegerField()),
                ('avg_clr_24_hr_vs_48', models.IntegerField()),
                ('avg_clr_48_hr_vs_7_day', models.IntegerField()),
                ('btc_sentiment_1_day', models.IntegerField()),
                ('btc_sentiment_2_days', models.IntegerField()),
                ('btc_sentiment_3_days', models.IntegerField()),
                ('btc_sentiment_7_days', models.IntegerField()),
                ('btc_sentiment_14_days', models.IntegerField()),
                ('btc_sentiment_30_days', models.IntegerField()),
                ('eth_sentiment_2_days', models.IntegerField()),
                ('eth_sentiment_3_days', models.IntegerField()),
                ('eth_sentiment_7_days', models.IntegerField()),
                ('eth_sentiment_14_days', models.IntegerField()),
                ('eth_sentiment_30_days', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('time_of_day', models.IntegerField()),
                ('good_bad', models.IntegerField()),
            ],
        ),
    ]
