# Generated by Django 2.0.7 on 2018-07-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadsheetmodel',
            name='ratio_bids_offers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='avg_clr_12_hr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='avg_clr_12_hr_vs_24',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='avg_clr_24_hr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='avg_clr_24_hr_vs_48',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='avg_clr_3_hr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='avg_clr_3_hr_vs_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='avg_clr_48_hr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='avg_clr_48_hr_vs_7_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='avg_clr_6_hr_vs_12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='avg_clr_7_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='btc_eth_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='btc_sentiment_14_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='btc_sentiment_1_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='btc_sentiment_2_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='btc_sentiment_30_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='btc_sentiment_3_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='btc_sentiment_7_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='btc_usd_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='clr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='consumed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='day_of_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='demand',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='demand_avg_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='eth_sentiment_14_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='eth_sentiment_2_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='eth_sentiment_30_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='eth_sentiment_3_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='eth_sentiment_7_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='eth_usd_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='good_bad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='number_of_bids_demand',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='number_of_offers_supply',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='percentage_of_available',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='rand_loan_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='rand_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='rand_term',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='ratio_demand_supply',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='simple_average_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='spread',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='supply',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='time_of_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheetmodel',
            name='weighted_average_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
