# Generated by Django 2.0.7 on 2018-09-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spreadsheet1',
            old_name='good_bad',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='spreadsheet10',
            old_name='good_bad',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='spreadsheet11',
            old_name='good_bad',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='spreadsheet12',
            old_name='good_bad',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='spreadsheet13',
            old_name='good_bad',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='spreadsheet14',
            old_name='good_bad',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='spreadsheet15',
            old_name='good_bad',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='spreadsheet16',
            old_name='good_bad',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='spreadsheet17',
            old_name='good_bad',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='spreadsheet18',
            old_name='good_bad',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='spreadsheet19',
            old_name='good_bad',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='spreadsheet2',
            old_name='good_bad',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='spreadsheet20',
            old_name='good_bad',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='spreadsheet3',
            old_name='good_bad',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='spreadsheet4',
            old_name='good_bad',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='spreadsheet5',
            old_name='good_bad',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='spreadsheet6',
            old_name='good_bad',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='spreadsheet7',
            old_name='good_bad',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='spreadsheet8',
            old_name='good_bad',
            new_name='good',
        ),
        migrations.RenameField(
            model_name='spreadsheet9',
            old_name='good_bad',
            new_name='good',
        ),
    ]
