# Generated by Django 2.0.7 on 2018-07-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180729_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadsheet1',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet10',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet11',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet12',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet13',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet14',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet15',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet16',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet17',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet18',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet19',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet2',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet20',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet3',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet4',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet5',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet6',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet7',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet8',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsheet9',
            name='date',
            field=models.DateTimeField(blank=True, max_length=120, null=True),
        ),
    ]
