# Generated by Django 2.0.7 on 2018-08-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180729_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadsheet1',
            name='labelled',
            field=models.BooleanField(default=False),
        ),
    ]
