# Generated by Django 2.0.7 on 2018-07-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20180720_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadsheet1',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet10',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet11',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet12',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet13',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet14',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet15',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet16',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet17',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet18',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet19',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet2',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet20',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet3',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet4',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet5',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet6',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet7',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet8',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
        migrations.AddField(
            model_name='spreadsheet9',
            name='loan_amount',
            field=models.DecimalField(blank=True, decimal_places=55, max_digits=60, null=True),
        ),
    ]
