# Generated by Django 2.0.7 on 2018-07-19 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20180719_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreadsheetmodel',
            name='spreadsheet',
        ),
        migrations.AddField(
            model_name='spreadsheet',
            name='worksheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.SpreadsheetModel'),
        ),
    ]
