# Generated by Django 2.0.7 on 2018-07-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20180719_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worksheets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='spreadsheet',
            name='worksheet',
            field=models.ManyToManyField(blank=True, to='webapp.SpreadsheetModel'),
        ),
        migrations.AddField(
            model_name='worksheets',
            name='worksheet_content',
            field=models.ManyToManyField(blank=True, to='webapp.SpreadSheet'),
        ),
    ]
