# Generated by Django 2.0.7 on 2018-07-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20180719_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spreadsheet',
            name='worksheet',
            field=models.ManyToManyField(blank=True, to='webapp.Worksheets'),
        ),
        migrations.AlterField(
            model_name='worksheets',
            name='worksheet_content',
            field=models.ManyToManyField(blank=True, to='webapp.SpreadsheetModel'),
        ),
    ]
