# Generated by Django 2.0.7 on 2018-07-19 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20180719_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksheets',
            name='worksheet_content',
        ),
        migrations.RemoveField(
            model_name='spreadsheet',
            name='worksheet',
        ),
        migrations.AddField(
            model_name='spreadsheetmodel',
            name='spreadsheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.SpreadSheet'),
        ),
        migrations.DeleteModel(
            name='Worksheets',
        ),
    ]
