# Generated by Django 2.0.7 on 2018-07-22 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20180722_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spreadsheet1',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='spreadsheet10',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='spreadsheet11',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='spreadsheet12',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='spreadsheet13',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='spreadsheet14',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='spreadsheet15',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='spreadsheet16',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='spreadsheet17',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='spreadsheet18',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='spreadsheet19',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='spreadsheet2',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='spreadsheet20',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='spreadsheet3',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='spreadsheet4',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='spreadsheet5',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='spreadsheet6',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='spreadsheet7',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='spreadsheet8',
            name='loan_number',
        ),
        migrations.RemoveField(
            model_name='spreadsheet9',
            name='loan_number',
        ),
    ]
